# fly.toml app configuration file generated for frameserve on 2025-04-23T00:47:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frameserve"
primary_region = "lhr"

[build]

[env]
  FSERVE_BIND_ADDRESS = "0.0.0.0:8080"
  FSERVE_BASE = "https://ctrl.caveh.tv"
  FSERVE_MEDIA_BASE = "https://media.caveh.tv"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = 256
